### PR TITLE
Fix package name.

### PR DESCRIPTION
**Pull request by cknitt**

### CODE REVIEW

**Comment by MoOx** [comment]
I was wondering if we wanted to go this way since we already cut a release with the other name.
Same for "core" package.

**Comment by cknitt** [comment]
I am leaning towards using `@reason-react-native/*` without exception.

I'd find it weird to have "mixed" names in my project's `package.json`, like

```
"dependencies": {
    "@reason-react-native/async-storage": "...",
    "@reason-react-native/deviceInfo": "...",
    "@reason-react-native/keychain": "...",
    // ... many other dependencies ...
    "reason-react-native": "...",
    "reason-react-native-navigation": "...",
    // ...
}
```

**Comment by MoOx** [comment]
Make sense. How should we rename `reason-react-native` then?

**Comment by cknitt** [comment]
I would say `@reason-react-native/react-native`.

**Comment by MoOx** [comment]
Oh good idea, it's simple.

Btw do we want to rename the repo "navigation" (& same for core repo) so repo match package name all the time?

**Comment by MoOx** [comment]
Hum never mind for navigation, I was thinking the package name was `@reason-react-native/navigation`.
Maybe that could seems inconsistant to sometimes have a short name (without react-(native-)) and sometimes not.

**Comment by cknitt** [comment]
It would be great to have the repo name always match the package name.

I just adapted the package name to the repo name though (`@reason-react-native/react-navigation`). If we want just `/navigation` instead of `/react-navigation`, we need to change both.

**Comment by MoOx** [comment]
/navigation would be good for me.

Exception would be react-native core bindings themselves I guess?

**Comment by cknitt** [comment]
That's fine with me!

**Comment by MoOx** [comment]
Will do the change soon & will notify everyone on discord when it's done.

**Pull request merged**
